# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ba2c932cf6717c8fb6207fcc8111fe70"
name = "CartUplift"
application_url = "https://cartuplift.com/"
embedded = true
handle = "cartupliftai"

[build]
automatically_update_urls_on_dev = false

[webhooks]
api_version = "2025-10"

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/data_request"
  compliance_topics = [ "customers/data_request" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/redact"
  compliance_topics = [ "customers/redact" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/shop/redact"
  compliance_topics = [ "shop/redact" ]

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "orders/create" ]
  uri = "/webhooks/orders/create"

  [[webhooks.subscriptions]]
  topics = [ "app_subscriptions/update" ]
  uri = "/webhooks/app-subscriptions/update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,read_products,read_themes"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://cartuplift.com/auth/callback",
  "https://cartuplift.com/auth/shopify/callback",
  "https://cartuplift.com/api/auth/callback"
]

[app_proxy]
url = "https://cartuplift.com/apps/proxy"
subpath = "cart-uplift"
prefix = "apps"

[pos]
embedded = false
